---
name: test pipeline

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Multiline-Command
        run: |
          node -v
          npm -v
      

